/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        CoffeeOrder coffeeOrder = new CoffeeOrder(SizeOption.MEDIUM,
                                                  CreamerOption.MILK,
                                   "Sugar");
        System.out.println("Coffee price is: " + coffeeOrder.price());

        CoffeeOrder coffeeOrder1 = new CoffeeOrder(SizeOption.LARGE,
                                                   CreamerOption.NONE,
                                   "Splenda");
        System.out.println("Coffee price is: " + coffeeOrder.price());

        CoffeeOrder coffeeOrder2 = new CoffeeOrder(SizeOption.XL,
                                                   CreamerOption.HALF_N_HALF,
                                   "Sugar");
        System.out.println("Coffee price is: " + coffeeOrder.price());

        CoffeeOrder coffeeOrder3 = new CoffeeOrder(SizeOption.SMALL,
                CreamerOption.NONE,0,
                "Sugar",3);
        System.out.println("Coffee price is: " + coffeeOrder.price());
    }
}
